server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.data\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/gzip;
    }

    location ~ \.js\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/javascript;
    }

    location ~ \.wasm\.gz$ {
        gzip off;
        add_header Content-Encoding gzip;
        default_type application/wasm;
    }
}